/**
 * processEventLog — System 12 of 12 in the tick pipe.
 *
 * Collects events generated by earlier systems and appends them
 * to the event log in chronological order.
 *
 * This runs last so it can capture events from all upstream systems.
 *
 * Pure function — no mutations, no side effects.
 */

import type { GameState } from '@idle-hero-rpg/shared';

export function processEventLog(state: GameState): GameState {
  // TODO: Implement event collection from state.pendingEvents
  // TODO: Append to state.eventLog and clear pendingEvents
  // TODO: Trim eventLog to max length to prevent unbounded growth
  return state;
}
