/**
 * processEventLog — System 12 of 12 in the tick pipe.
 *
 * Collects events generated by earlier systems and appends them
 * to the event log in chronological order.
 *
 * This runs last so it can capture events from all upstream systems.
 *
 * Pure function — no mutations, no side effects.
 */

import type { GameState } from '@idle-hero-rpg/shared';
import { EVENT_LOG_MAX_LENGTH } from '../data/balance';

export function processEventLog(state: GameState): GameState {
  // Nothing to do if no pending events
  if (state.pendingEvents.length === 0) {
    return state;
  }

  // Append pending events to the log
  const combined = [...state.eventLog, ...state.pendingEvents];

  // Trim from the front (oldest first) to stay within max length
  const trimmed =
    combined.length > EVENT_LOG_MAX_LENGTH
      ? combined.slice(combined.length - EVENT_LOG_MAX_LENGTH)
      : combined;

  return {
    ...state,
    eventLog: trimmed,
    pendingEvents: [],
  };
}
